apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: same-ip-services
  template:
    metadata:
      namespace: default
      labels:
        app: same-ip-services
    spec:
      containers:
        - name: menu-service-ui
          image: northamerica-northeast1-docker.pkg.dev/enuatv/containers/menu-service-ui:${GIT_SHA}
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "264M"
            limits:
              memory: "300M"
#          volumeMounts:
#            - name: artifact-registry-service-account
#              mountPath: /secrets/artifact-registry
#              readOnly: true
#      volumes:
#        - name: artifact-registry-service-account
#          secret:
#            secretName: artifact-registry-service-account
