apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-service-ui
  template:
    metadata:
      namespace: default
      labels:
        app: menu-service-ui
    spec:
      containers:
        - name: menu-service-ui
          image: northamerica-northeast1-docker.pkg.dev/enuatv/containers/menu-service-ui:${GIT_SHA}
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              ephemeral-storage: "128M"
              memory: "264M"
            limits:
              cpu: "200m"
              ephemeral-storage: "256M"
              memory: "300M"
#          volumeMounts:
#            - name: artifact-registry-service-account
#              mountPath: /secrets/artifact-registry
#              readOnly: true
#      volumes:
#        - name: artifact-registry-service-account
#          secret:
#            secretName: artifact-registry-service-account
