---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "menu-service-ui"
  namespace: "main"
spec:
  ports:
    - protocol: "TCP"
      name: "menu-port3000"
      port: 3000
      targetPort: 3000
  selector:
    app: "menu-service-ui"
  type: "LoadBalancer"
