name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_SERVICE_ACCOUNT: ${{ secrets.GKE_SERVICE_ACCOUNT }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GCP_ARTIFACT_REGISTRY_SA_DEVELOPMENT: ${{ secrets.GCP_ARTIFACT_REGISTRY_SA_DEVELOPMENT }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  IMAGE: menu-service-ui
  GIT_SHA: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Install package from Google Artifact Registry
        run: |
          jq -n '${{ env.GCP_ARTIFACT_REGISTRY_SA_DEVELOPMENT }}' > file.json > artifact-registry-service-account.json
          cat artifact-registry-service-account.json

#      - id: "auth"
#        uses: 'google-github-actions/auth@v0'
#        with:
#          credentials_json: '${{ secrets.GCP_ARTIFACT_REGISTRY_SA_DEVELOPMENT }}'

      - name: Set up GCP and get cluster credentials
        run: |
          gcloud auth activate-service-account --key-file=./artifact-registry-service-account.json
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t "northamerica-northeast1-docker.pkg.dev/enuatv/containers/menu-service-ui:$GIT_SHA" \
                       -t "northamerica-northeast1-docker.pkg.dev/enuatv/containers/menu-service-ui:latest" \
                       --build-arg GIT_SHA=$GIT_SHA \
                       --build-arg NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }} \
                       --build-arg GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }} \
                       --build-arg GOOGLE_CLIENT_SECRET=${{ env.GOOGLE_CLIENT_SECRET }} .
          docker push "northamerica-northeast1-docker.pkg.dev/enuatv/containers/menu-service-ui:$GIT_SHA"

      - name: Install and configure kubectl
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud components install kubectl
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}

      - name: Deploy to Kubernetes
        run: |
          cd k8s
          envsubst < deployment.template.yaml > deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/menu-merchant-api --namespace default
